name: Sync Claude & AI Tooling

on:
  workflow_dispatch:

jobs:
  sync-tooling:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Checkout acg-development-tooling repository
        uses: actions/checkout@v4
        with:
          repository: loy-misquith-frequence/acg-development-tooling
          path: source-repo

      - name: Sync .claude directory
        run: |
          rsync -av --delete source-repo/.claude/ .claude/ || true

      - name: Sync ai directory
        run: |
          rsync -av --delete --exclude='frequence_api_context/' --exclude='frequence_platform_context/' --exclude='tickets/' source-repo/ai/ ai/ || true

      - name: Commit & Push if changes
        run: |
          git config user.name "loymisquith ACG Bot"
          git config user.email "loymisquith@acg-bot.com"
          [ -d .claude ] && git add .claude
          [ -d ai ] && git add ai
          if ! git diff --cached --quiet; then
            git commit -m "Sync .claude and ai from acg-development-tooling"
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi
